export const DEFAULT_KATAGO_VISITS = 5_000
export const DEFAULT_BENCHMARK_TRAINING_VISITS = 10_000
export const DEFAULT_NOTEBOOK_TOKEN_BUDGET = 2_000
export const DEFAULT_NOTEBOOK_INITIALIZATION_TOKEN_LIMIT = 3_000
